version: "3.3"
services:
  personal-website:
    image: nix-personal-website:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    container_name: "nixie_personal_website"